
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module C5G_sevenseg(

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3
);



//=======================================================
//  REG/WIRE declarations
//=======================================================


//=======================================================
//  Structural coding
//=======================================================

sevenseg 		sevenseg_u0
(
	.bin_i 			(SW [3:0]),		// LSB for hex0
	.hex_o 			(),				// empty, NC
	.hexn_o			(HEX0)			// right most display
);

sevenseg 		sevenseg_u1
(
	.bin_i 			(SW [7:4]),		// LSB for hex1
	.hex_o 			(),				// empty, NC
	.hexn_o			(HEX1)			// second right most display
);

assign HEX2 = '1;	// turn off the LED
assign HEX3 = '1;	// turn off the LED

endmodule
